In [1]:
L = [1, 2, 3, 8, 7, 11]
len(L)

6

In [2]:
import math as m
p = m.pi
L[2] = p
print(L)

[1, 2, 3.141592653589793, 8, 7, 11]


In [8]:
y = m.cos(L[2])
List_cos = []
for i in range (len(L)):
    x = m.cos(L[i])
    List_cos.append(x)
print(List_cos)

[0.5403023058681398, -0.4161468365471424, -1.0, -0.14550003380861354, 0.7539022543433046, 0.004425697988050785]


In [9]:
List_cos = [m.cos(L[i]) for i in range (len(L))]
print(List_cos)

[0.5403023058681398, -0.4161468365471424, -1.0, -0.14550003380861354, 0.7539022543433046, 0.004425697988050785]


In [12]:
n = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
n[1][2] = m.pi/2
print(n)

[[1, 2, 3], [4, 5, 1.5707963267948966], [7, 8, 9]]


In [14]:
def List_cos(L):
    L0 = []
    for i in range (len(L)):
        L1 = []
        for j in range (len(L)):
            L1.append(m.cos(L[i][j]))
        L0.append(L1)
    
    return L0
print(List_cos(n))

[[0.5403023058681398, -0.4161468365471424, -0.9899924966004454], [-0.6536436208636119, 0.28366218546322625, 6.123233995736766e-17], [0.7539022543433046, -0.14550003380861354, -0.9111302618846769]]


In [15]:
import numpy as np
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__git_version__',
 '__loader__',

In [16]:
u = np.array([1, 2, 3])
print(u)

[1 2 3]


In [17]:
print(u.shape) # ou bien np.shape(u)

(3,)


In [18]:
m = np.array([[2.0, 4.0, 6.0],
              [1.0, 2.0, 3.0],
              [4.0, 7.0, 9.0]])
print(m.shape)

(3, 3)


In [19]:
m.size

9

In [20]:
m.dtype

dtype('float64')

In [21]:
u.dtype

dtype('int32')

In [22]:
v = np.array([[1], [2], [3]])
v.shape

(3, 1)

In [23]:
V = np.transpose(v) # v.T
M = m.T
print(V.shape)
print(M.shape)
Y = np.cos(M)
print(Y)

(1, 3)
(3, 3)
[[-0.41614684  0.54030231 -0.65364362]
 [-0.65364362 -0.41614684  0.75390225]
 [ 0.96017029 -0.9899925  -0.91113026]]


In [24]:
Z = np.sqrt(Y)
print(Z)

[[       nan 0.73505259        nan]
 [       nan        nan 0.86827545]
 [0.97988279        nan        nan]]


C:\Users\hafeu\AppData\Local\Temp\ipykernel_13876\1887328626.py:1: RuntimeWarning: invalid value encountered in sqrt
  Z = np.sqrt(Y)


In [25]:
Y * Z

array([[       nan, 0.39715061,        nan],
       [       nan,        nan, 0.65459482],
       [0.94085434,        nan,        nan]])

Y + Z 

In [27]:
np.dot(Y, Z)

array([[nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan]])

In [28]:
np.cross(Y, Z)

array([[nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan]])

In [30]:
a = M[:, 1]
print(a)

[1. 2. 3.]


In [31]:
b = M[1, 1:]
print(b)

[2. 7.]


In [32]:
print(M)

[[2. 1. 4.]
 [4. 2. 7.]
 [6. 3. 9.]]


In [33]:
x = np.linalg.inv(M).dot(b)
print(x)

LinAlgError: Singular matrix