In [29]:
import numpy as np
import sympy as sp
import matplotlib.pyplot as plt
import pandas as pd
from numpy.polynomial import Polynomial

In [20]:
np.ones((3, 2), int)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [22]:
A = 5*diagflat(3)
print(A)

NameError: name 'diagflat' is not defined

In [21]:
B = 2 * np.diagflat(np.ones(n-1),1)
print(B)

[[0. 2. 0.]
 [0. 0. 2.]
 [0. 0. 0.]]


In [26]:
print(np.shape(B))

(3, 3)


In [31]:
P=Polynomial([2,3,1])
P

Polynomial([2., 3., 1.], domain=[-1,  1], window=[-1,  1], symbol='x')