In [37]:
#2 Applications numériques
import numpy as np

#Question 1, a
def tridiag(a1, a2, a3, n):
    A = a1*np.eye(n) + a2*np.diagflat(np.ones(n-1), 1) + a3*np.diagflat(np.ones(n-1), -1)
    b = 2*np.ones((n, 1))
    return A,b

In [106]:
#b
a1,a2,a3,n=4,1,1,10
tridiag(a1,a2,a3,n)

(array([[4., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 4., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 4., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 4., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 4., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 4., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 4., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 4., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 4., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 4.]]),
 array([[2.],
        [2.],
        [2.],
        [2.],
        [2.],
        [2.],
        [2.],
        [2.],
        [2.],
        [2.]]))

In [74]:
#Question 2, a
def matrice_diag_dominante(B):
    etat = True
    for i in range(np.shape(B)[0]):
        if(np.abs(B[i, i]) < np.sum(np.abs(B[i,:])) - np.abs(B[i, i])):
            etat = False
    return etat

B = np.array([[7, 4, -2], [5, 9, 3], [4, -3, -8]])
print(matrice_diag_dominante(B))

True


In [80]:
#b
B1 = tridiag(4, 1, 1, 10)[0]
B2 = tridiag(1, 1, 1, 10)[0]
print(matrice_diag_dominante(B1))
print(matrice_diag_dominante(B2))

True
False


In [95]:
#Question 3, a
def jacobi(B, b1, X0, epsilon):
    if(matrice_diag_dominante(B) == False):
        return "B n'est pas diagonale strictement dominante"
    else:
        M = np.diagflat(np.diag(B))
        N = B - M
        inv_M = np.linalg.inv(M)
        D = inv_M.dot(N)
        C = inv_M.dot(b1)
        iterations = 0
        while(np.linalg.norm(B.dot(X0) - b1, 1) <= epsilon):
            iterations += 1
            X1 = D.dot(X0) + C
            X0 = X1
        return iterations, X0

In [107]:
#b
n=10
X0=np.ones((n,1))
epsilon=10**-6
b1=tridiag(a1,a2,a3,n)[1]
B=tridiag(a1,a2,a3,n)[0]
jacobi(B, b1, X0, epsilon)

(0,
 array([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]]))