In [7]:
import numpy as np #Pour les manipulations numériques
import matplotlib.pyplot as plt

#2 - Applications Numériques

#Question 1, a:
def tridiag(a1, a2, a3, n):
    A = a1 * np.eye(n) + a2 * np.diagflat(np.ones(n-1), 1) + a3 * np.diagflat(np.ones(n-1), -1) #diagflat +1 or -1, tatla3 feka el star eli fou9 el diagonal, 9bi7a barcha
    b = np.ones((n,1))*2
    
    return (A, b)

#Question 1, b:
a1, a2, a3, n = 4, 1, 1, 10
(A, b) = tridiag(a1, a2, a3, n)
print(A)
print(b)

[[4. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 4. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 4. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 4. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 4. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 4. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 4. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 4. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 4. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 4.]]
[[2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]]
